openapi: 3.0.0
paths:
  /content:
    get:
      operationId: ContentController_getAllContentList
      parameters: []
      responses:
        '200':
          description: コンテンツ一覧を取得します
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
      summary: コンテンツ一覧の取得
      tags:
        - Content
    post:
      operationId: ContentController_addContent
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContentDTO'
      responses:
        '201':
          description: 新しいコンテンツが作成されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
      summary: コンテンツの作成
      tags:
        - Content
  /content/{id}:
    get:
      operationId: ContentController_getContent
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: 指定されたIDのコンテンツを取得します
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
      summary: コンテンツの取得
      tags:
        - Content
    put:
      operationId: ContentController_updateContent
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContentDTO'
      responses:
        '200':
          description: コンテンツが更新されました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
      summary: コンテンツの更新
      tags:
        - Content
    delete:
      operationId: ContentController_deleteContent
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '204':
          description: コンテンツが削除されました
      summary: コンテンツの削除
      tags:
        - Content
info:
  title: Frontend Recruit
  description: ''
  version: '1.0'
  contact: {}
tags:
  - name: frontend
    description: ''
servers: []
components:
  schemas:
    Content:
      type: object
      properties:
        id:
          type: number
          description: コンテンツのID
          example: 1
        title:
          type: string
          description: コンテンツのタイトル
          example: Hello Title
          nullable: true
        body:
          type: string
          description: コンテンツの本文
          example: Hello Body
          nullable: true
        createdAt:
          format: date-time
          type: string
          description: 作成日時
          example: '2025-04-04T00:00:00.000Z'
        updatedAt:
          format: date-time
          type: string
          description: 更新日時
          example: '2025-04-04T00:00:00.000Z'
      required:
        - id
        - title
        - body
        - createdAt
        - updatedAt
    CreateContentDTO:
      type: object
      properties:
        title:
          type: string
          description: コンテンツのタイトル
          example: Hello Title
        body:
          type: string
          description: コンテンツのボディ
          example: Hello Body
      required:
        - title
        - body
    UpdateContentDTO:
      type: object
      properties:
        title:
          type: string
          description: コンテンツのタイトル
          example: Update Title
        body:
          type: string
          description: コンテンツのボディ
          example: Update Body
      required:
        - title
        - body
